language: python

install:
  - pip install tox

script:
  - tox

env:
  - TOXENV=py26-django15
  - TOXENV=py26-django16
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py32-django15
  - TOXENV=py32-django16
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py34-django15
  - TOXENV=py34-django16
  - TOXENV=py27-django17
  - TOXENV=py32-django17
  - TOXENV=py33-django17
  - TOXENV=py34-django17
  - TOXENV=coverage
